### ISSUE TITLE
关于FewJoint1.0和FewJoint1.1的区别

### ISSUE THREAD

**Issue by chenshaowei57** [AtmaHou/FewShotJoint#2]
作者您好，我发现您提供的数据集包含了FewJoint1.0和FewJoint1.1两个数据集，想询问一下两者的区别

**Comment by AtmaHou** [comment]
前者是ACL21文章和SMP2019比赛用的版本，后来发现有1-2个domain 5shot 样例不够，又补标了一些，就有了第二个版本。

**Comment by wjczf123** [comment]
Does this mean that FewJoint 1.1 is more suitable for the benchmark dataset?
